# Site settings
# in the templates available like {{ site.myvariable }}.
title: Happy Birthday to you!
email: sweetcadbury@gmail.com
# brand: This One For You 
headline: Inventor, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2018 &copy Chaitu&Cadbury, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: sweetcadbury@gmail.com
phone: +91-9834653974

# Tracking
googleAnalitycsID: UA-83933844-1

